# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kcalendarcore' : '@latest'
    'kde/pim/akonadi' : '@latest'
    'kde/pim/kcalutils' : '@latest'
    'kde/pim/kidentitymanagement' : '@latest'
