# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/kcalendarcore' : '@latest'
    'kde/pim/akonadi' : '@latest'
    'kde/pim/akonadi-contacts' : '@latest'
    'kde/pim/akonadi-mime' : '@latest'
    'kde/pim/kalarmcal' : '@latest'
    'kde/pim/kcalutils' : '@latest'
    'kde/pim/kidentitymanagement' : '@latest'
    'kde/pim/kimap' : '@latest'
    'kde/pim/kmailtransport' : '@latest'
    'kde/pim/kmime' : '@latest'
    'kde/pim/kpimtextedit' : '@latest'
    'kde/pim/libkdepim' : '@latest'
    'kde/pim/mailcommon' : '@latest'
    'kde/pim/pimcommon' : '@latest'
