# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'kde/pim/akonadi' : '@same'
    'kde/pim/akonadi-contacts' : '@same'
    'kde/pim/akonadi-mime' : '@same'
    'kde/pim/kalarmcal' : '@same'
    'kde/pim/kcalutils' : '@same'
    'kde/pim/kidentitymanagement' : '@same'
    'kde/pim/kimap' : '@same'
    'kde/pim/kmailtransport' : '@same'
    'kde/pim/kmime' : '@same'
    'kde/pim/kpimtextedit' : '@same'
    'kde/pim/mailcommon' : '@same'
    'kde/pim/pimcommon' : '@same'
