# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': 'Frameworks/6.24'
    'frameworks/kcalendarcore': 'Frameworks/6.24'
    'frameworks/kholidays': 'Frameworks/6.24'
    'frameworks/kcodecs': 'Frameworks/6.24'
    'frameworks/kcompletion': 'Frameworks/6.24'
    'frameworks/kconfig': 'Frameworks/6.24'
    'frameworks/kconfigwidgets': 'Frameworks/6.24'
    'frameworks/kcontacts': 'Frameworks/6.24'
    'frameworks/kcrash': 'Frameworks/6.24'
    'frameworks/kdbusaddons': 'Frameworks/6.24'
    'frameworks/kguiaddons': 'Frameworks/6.24'
    'frameworks/ki18n': 'Frameworks/6.24'
    'frameworks/kitemmodels': 'Frameworks/6.24'
    'frameworks/kjobwidgets': 'Frameworks/6.24'
    'frameworks/kio': 'Frameworks/6.24'
    'frameworks/knotifications': 'Frameworks/6.24'
    'frameworks/knotifyconfig': 'Frameworks/6.24'
    'frameworks/kservice': 'Frameworks/6.24'
    'frameworks/kwidgetsaddons': 'Frameworks/6.24'
    'frameworks/kwindowsystem': 'Frameworks/6.24'
    'frameworks/kxmlgui': 'Frameworks/6.24'
    'frameworks/kstatusnotifieritem': 'Frameworks/6.24'
    'frameworks/kiconthemes': 'Frameworks/6.24'
    'pim/akonadi': '@same'
    'pim/akonadi-contacts': '@same'
    'pim/akonadi-mime': '@same'
    'pim/kcalutils': '@same'
    'pim/kidentitymanagement': '@same'
    'pim/kmailtransport': '@same'
    'pim/kmime': '@same'
    'libraries/ktextaddons': '@latest-kf6'

 - 'on': ['Linux', 'FreeBSD']
   'require':
    'frameworks/kglobalaccel': 'Frameworks/6.24'

Options:
 require-passing-tests-on: ['@all']
 cppcheck-arguments: '--enable=warning,style,performance --inline-suppr'
