# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'frameworks/kholidays' : '@latest'
    'pim/akonadi' : '@same'
    'pim/akonadi-contacts' : '@same'
    'pim/akonadi-mime' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kidentitymanagement' : '@same'
    'pim/kimap' : '@same'
    'pim/kmailtransport' : '@same'
    'pim/kmime' : '@same'
    'pim/kpimtextedit' : '@same'
    'pim/mailcommon' : '@same'
    'pim/pimcommon' : '@same'
