# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest'
    'frameworks/kcalendarcore' : '@latest'
    'frameworks/kholidays': '@latest'
    'frameworks/ki18n': '@latest'
    'frameworks/kconfig': '@latest'
    'pim/akonadi' : '@same'
    'pim/kcalutils' : '@same'
    'pim/kidentitymanagement' : '@same'
