/* config-kalarm.h. Generated by cmake from config-kalarm.h.cmake */

/* Define to 1 if building with Xlib */
#cmakedefine01 ENABLE_X11

/* Define to 1 if wake-from-suspend is enabled */
#cmakedefine01 ENABLE_WAKE_FROM_SUSPEND
