/* config-kalarm.h. Generated by cmake from config-kalarm.h.cmake */

/* Define to 1 if you have the Xlib */
#cmakedefine01 KDEPIM_HAVE_X11

/* Define to 1 if wake-from-suspend is enabled */
#cmakedefine01 ENABLE_WAKE_FROM_SUSPEND
